version: 3


pullapprove_conditions:
- condition: "'*travis*' in statuses.successful"
  unmet_status: failure
  explanation: "Tests must pass before review starts"

# DISABLED: pullapprove v3 has not yet added support for "Githubb Checks" which are how Github Apps return status of tests
# In the meantime we will enforce these tests within Github itself
#- condition: "'*jenkins*' in statuses.successful"
#  unmet_status: failure
#  explanation: "Tests must pass before review starts"

groups:
  pullapprove-admins:
    conditions:
    - "'.pullapprove.yml' in files"

    reviews:
      required: 1
      author_value: 1 # if author in group reduce number of approvals needed by this number

    reviewers:
      users:
      - rhiananthony
      teams:
      - secops

  software-review:
    reviews:
      required: 2
      author_value: 1 # if author in group reduce number of approvals needed by this number
      request_order: random  # reviewers will be chosen in a random order

    reviewers:
      teams:
      - pipelines-software-engineers-hornet
      - pipelines-devops

#  computational-review:
#    reviews:
#      required: 1
#      author_value: 1 # if author in group reduce number of approvals needed by this number
#      request_order: random  # reviewers will be chosen in a random order
#
#    reviewers:
#      teams:
#      - pipelines-computational-biologists

notifications:
- when: pullapprove.approved
  if: "author_association == 'CONTRIBUTOR'"
  comment: "The review is completed. Thanks @{{ author }}."
