language: python
python:
- '2.7'
- '3.6'
install: pip install -r requirements.txt -r test-requirements.txt
script: python -m unittest discover -v
notifications:
  slack:
    on_success: change
    on_failure: always
    rooms:
      secure: qH9+hm1iKQxbLtTxQ+2nW1daVnSzTJbHoSH77PbkyWskqI8ovylZ5nxYAd//gNtgXYEVz2plVW9x8EjuK/cdYG33tqRJoueQVyLVUXbPf2ptQ029z2H/l2SXy59beQdBBVQaQal6WgGijbT2nWuL5x8GnM01cC86TvU7z8sJl7gWSC5KCmcqhKmtScUZDri6kRuZMR27v09MuDhO/W1ObBlS5/D1APKivJZqVC3g1hy3dvOSFfeHyHzM6tQxlvm8JAvyc0BV4qMJkTiM80/NMn185fDl+IKr5wMCC4aNUn3JDu3haIuemvyAKBor6i8dKEabQ971fDU3wTWSxXD9A2H7IxRsKHiFwEZfVBz3/YS11bsKf6Ppsfltb4b84iC7V/In5vicUSJX4y9mhMrvxYBGG3ElnMCOmAUQtKKKYqj7Oeo5gKNc4LNe0i5egbLL1RGBUfgeSwLAp8KzasDwdcM9CvxIdCg3WFHxZCY2q2jf79u8mAdYr7Lsfr8wgDGMl8JytCAanlETXCG1GrWq0ntBqVWoi2VXVhM3PLhyTIq1FiqROMXhSWjotzT+o5JtUi283tW18F81Hs+zl3yf0YkSYOPB+aynb6A4qGc4cZ9VlGXtow9erbyWa2RED67GM29MKwKwRPfZ6CWIwrb58b/MIs/1D+mJaKv2osppkZ4=
