name: CI

on:
  push:
  pull_request:

jobs:
  linting-test:
    name: Linting Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.6'
      - run: pip install -U setuptools && pip install -r requirements.txt
      - run: black pipeline_tools/ --skip-string-normalization --check
      - run: flake8

  unit-test:
    name: Unit Test
    runs-on: ubuntu-latest
    needs: linting-test
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.6'
      - run: pip install -U setuptools && pip install -r requirements.txt
      - run: pytest -v